### ISSUE TITLE
build error: WebPDecodeRGBA Not Found while linking

### ISSUE THREAD

**Issue by Pro-YY** [dbasedow/react-native-webp#1]
I've got this build error, could you please help me?

`Undefined symbols for architecture arm64:
  "_WebPDecodeRGBA", referenced from:
      -[DBAWebpImageDecoder decodeImageData:size:scale:resizeMode:completionHandler:] in libReactNativeWebp.a(DBAWebpImageDecoder.o)
  "_WebPGetInfo", referenced from:
      -[DBAWebpImageDecoder canDecodeImageData:] in libReactNativeWebp.a(DBAWebpImageDecoder.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by dbasedow** [comment]
It sounds like you did not add the WebP.framework to the XCode project or it was removed for some reason. Could you try running steps 3 - 8 of the installation instructions again?

**Comment by Pro-YY** [comment]
Perfect! Thank you so much.
This is an excellent project. Thanks!
