### ISSUE TITLE
Can not show .webp image on ios

### ISSUE THREAD

**Issue by wuhenzhizao** [dbasedow/react-native-webp#15]
I did as the Installation Guide said，no error, no warning, but nothing show，the react-native version is  '0.54.3'，could you provide a demo ?

**Comment by kira1928** [comment]
Hi @wuhenzhizao ,
I have tested this lib in react-native 0.54.0, which worked correctly.
Could you provide your project or a similar demo project which has the same problem?

**Comment by wuhenzhizao** [comment]
replace code in node_modules/react-native-webp with the newest commit, it works well
