### ISSUE TITLE
NOTICE: please use react-native-webp-support-npm replacement react-native-webp

### ISSUE THREAD

**Issue by Kennytian** [dbasedow/react-native-webp#16]
please use `react-native-webp-support-npm` replacement `react-native-webp`, because `react-native-webp` packages missing `WebPDemux.framework`

**Comment by EskelCz** [comment]
@Kennytian Are you sure? The framework is here in the repo
https://github.com/dbasedow/react-native-webp/tree/master/WebPDemux.framework

**Comment by Kennytian** [comment]
@EskelCz  Maybe not include project.pbxproj,  I'm not spot it in

https://github.com/dbasedow/react-native-webp/blob/master/ReactNativeWebp.xcodeproj/project.pbxproj

**Comment by Aleksefo** [comment]
@Kennytian @EskelCz I've published a new WebP integration library. It supports the latest React Native version, Cacaopods and auto-linking and has better native libraries for a performance boost.
Please check it out [https://github.com/Aleksefo/react-native-webp-format](https://github.com/Aleksefo/react-native-webp-format)

**Comment by Kennytian** [comment]
@Aleksefo  Good job, thanks buddy!
