### ISSUE TITLE
memory leak when render dynamic source image

### ISSUE THREAD

**Issue by Pro-YY** [dbasedow/react-native-webp#2]
The following code would end with memory leak ('Received Memory Warning'), when changing the **PIC0** and **PIC1** to a webp format image url.

```
import React, {
    AppRegistry,
    Component,
    StyleSheet,
    Text,
    View,
    Image
} from 'react-native';

const PIC0 = 'https://pmcdeadline2.files.wordpress.com/2014/06/twitter-logo.png';
const PIC1 = 'https://avatars0.githubusercontent.com/u/69631';

class Issue extends Component {
    constructor(props) {
        super(props);
        this.state = {uri: PIC0};
    }
    componentDidMount() {
        setInterval(() => {
            let p = ~~(Math.random()*100)%2 ? PIC0 : PIC1;
            console.log(p);
            this.setState({uri: p});
        }, 100);
    }

    render() {
        console.log('render');
    return (
        <View style={styles.container}>
            <Image style={styles.image} source={{uri: this.state.uri}}/>
        </View>
    );
  }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
    },
    image: {
        width: 400,
        height: 400,
    }
});
```

**Comment by dbasedow** [comment]
Thanks for bringing this to my attention! I added some code to free memory manually.

Your example is still slowly leaking some memory. But it seems to be a react-native problem, as it also happens with the PNGs.

**Comment by weepy** [comment]
@dbasedow - I'm running into the issue of PNGs leaking in RN. Do you know if there's a way to deallocate them ?!

**Comment by h2soheili** [comment]
> Thanks for bringing this to my attention! I added some code to free memory manually.
> 
> Your example is still slowly leaking some memory. But it seems to be a react-native problem, as it also happens with the PNGs.

could to share your solution ?
