### ISSUE TITLE
Timeline on Android Support

### ISSUE THREAD

**Issue by c-h-** [dbasedow/react-native-webp#3]
Is there any plans to add Android support for this project?

**Comment by dbasedow** [comment]
Android has supported WebP natively since 4.0. Lossless and transparency were added in 4.2.1 according to https://developer.android.com/guide/appendix/media-formats.html

For me WebP images work on Android without doing anything. Do you have to support 4.1?

**Comment by c-h-** [comment]
Turns out there was an issue with the WebP source.

I do actually need to support Android down to Froyo (2.2).

Perhaps implementing https://github.com/EverythingMe/webp-android for React Native Android support would be worthwhile?

**Comment by dbasedow** [comment]
Android uses Fresco for loading images, so this should solve your problem: http://frescolib.org/docs/webp-support.html

As far as I know you won't be able to support Froyo, RN requires Android >=4.1

**Comment by c-h-** [comment]
Thank you for the help!!
