### ISSUE TITLE
header search path for release

### ISSUE THREAD

**Issue by Poordeveloper** [dbasedow/react-native-webp#6]
Could you please modify header search path for release same to debug?

**Comment by dbasedow** [comment]
Release and Debug Header Search Path are already identical. What exactly do you need?

**Comment by Poordeveloper** [comment]
npm version not updated

**Comment by Poordeveloper** [comment]
Thanks, I will use npm install https://github.com/dbasedow/react-native-webp.git --save instead npm install react-native-webp

**Comment by dbasedow** [comment]
Oh, you're right I haven't updated npm in a while. I just published the current master branch. So you won't have to directly depend on this repo.
